[package]
name = "liora-components"
version = "0.2.7"
edition = "2024"
description = "Enterprise-style native GPUI component library for Liora applications."
license-file = "../../LICENSE.md"
repository = "https://github.com/yhyzgn/liora"
readme = "README.md"
publish = true

[dependencies]
gpui.workspace = true
liora-core = { version = "0.2.7", path = "../liora-core" }
liora-theme = { version = "0.2.7", path = "../liora-theme" }
liora-icons = { version = "0.2.7", path = "../liora-icons" }
liora-icons-lucide = { version = "0.2.7", path = "../liora-icons-lucide" }
image = "0.25"
qrcode = "0.14"
rqrr = "0.8"
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
lyon_tessellation = "1.0"
ureq = "2"
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }
two-face = { version = "0.5.1", default-features = false, features = ["syntect-default-fancy"] }
tree-sitter.workspace = true
tree-sitter-json.workspace = true
tree-sitter-md.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-typescript.workspace = true
